SELECT 
    COLUMN_NAME AS 'COLUMN_NAME',
    COLUMN_TYPE AS 'COLUMN_TYPE',
    IS_NULLABLE AS 'IS_NULLABLE',
    COLUMN_DEFAULT AS 'COLUMN_DEFAULT',
    COLUMN_KEY AS 'COLUMN_KEY',
    EXTRA AS 'EXTRA'
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'alx_book_store'
  AND TABLE_NAME = 'Books'
ORDER BY ORDINAL_POSITION;
